// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq04w1PBrM2FSGCDPR7H8lNlqZGRI7Ews',
    appId: '1:807668182958:web:542ce3fee05ada7a73a23f',
    messagingSenderId: '807668182958',
    projectId: 'memory-book-ec469',
    authDomain: 'memory-book-ec469.firebaseapp.com',
    storageBucket: 'memory-book-ec469.firebasestorage.app',
    measurementId: 'G-BED9WZYSKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbslH5pMv1Md38GVk0xLSpL9IA6YazFTE',
    appId: '1:807668182958:android:b60191399b073bf473a23f',
    messagingSenderId: '807668182958',
    projectId: 'memory-book-ec469',
    storageBucket: 'memory-book-ec469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-0qEz7S7zcSm2H9LTmAhnrGlPYVzKsqo',
    appId: '1:807668182958:ios:604c8bcccf4c582473a23f',
    messagingSenderId: '807668182958',
    projectId: 'memory-book-ec469',
    storageBucket: 'memory-book-ec469.firebasestorage.app',
    iosBundleId: 'com.maxdev.memoryBook',
  );
}
